name: testing metrics

on:
  workflow_dispatch:

jobs:
  output-job-id-and-wait:
    runs-on: ubuntu-latest
    steps:
      - name: get job id
        run: |
          # Used to get the job id. Job id needed for making the URL inside of the JSON
          # Using jq searches for the name of the job and gets the corresponding job id attached to the name.
          echo "job-id=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github_token_api }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | jq '.jobs[] | select(.name | test("^${{ inputs.job_name }}$"; "i")) | .id')" >> "${GITHUB_ENV}"

      - name: echo job id
        run: |
          echo "${job-id}"

      - name: wait set amount of time
        run: |
          wait 200
